const course={
uk:{start:"Розпочати курс",prev:"Назад",next:"Далі",sections:[
{title:"Вступ",lead:"Що таке Deep Learning і навіщо воно потрібне",body:`<div class="learning"><strong>Навчальна мета</strong><p>Після цього розділу ви зможете пояснити, що таке глибоке навчання та чому воно стало важливим напрямом штучного інтелекту.</p></div><h3>Глибоке навчання — коротко</h3><p>Deep Learning — це підхід машинного навчання, у якому багатошарові нейронні мережі навчаються знаходити складні закономірності у великих обсягах даних.</p><div class="flow"><span>Дані</span><b>→</b><span>Нейронна мережа</span><b>→</b><span>Навчання</span><b>→</b><span>Результат</span></div><div class="check"><h3>Міні-перевірка</h3><p>Що найкраще описує Deep Learning?</p><button class="answer" data-correct="0">Набір жорстко заданих правил</button><button class="answer" data-correct="1">Навчання багатошарової нейронної мережі на даних</button><button class="answer" data-correct="0">Звичайне зберігання великих масивів даних</button><p class="feedback"></p></div>`},
{title:"AI → ML → Deep Learning",lead:"Як пов’язані ключові поняття",body:`<p>Штучний інтелект — найширше поняття. Machine Learning є його підмножиною, а Deep Learning — підмножиною машинного навчання.</p><div class="concepts"><article><b>AI</b><p>Системи, що виконують завдання, які потребують інтелектуальної поведінки.</p></article><article><b>ML</b><p>Алгоритми, які навчаються закономірностям із даних.</p></article><article><b>DL</b><p>ML на основі багатошарових нейронних мереж.</p></article></div><div class="takeaway"><strong>Запам’ятайте:</strong> Deep Learning ⊂ Machine Learning ⊂ Artificial Intelligence.</div>`}
]},
en:{start:"Start course",prev:"Back",next:"Next",sections:[
{title:"Introduction",lead:"What Deep Learning is and why it matters",body:`<div class="learning"><strong>Learning objective</strong><p>After this section, you will be able to explain what deep learning is and why it has become an important field of artificial intelligence.</p></div><h3>Deep Learning — in brief</h3><p>Deep Learning is a machine-learning approach in which multi-layer neural networks learn complex patterns from large amounts of data.</p><div class="flow"><span>Data</span><b>→</b><span>Neural Network</span><b>→</b><span>Learning</span><b>→</b><span>Result</span></div><div class="check"><h3>Mini check</h3><p>Which statement best describes Deep Learning?</p><button class="answer" data-correct="0">A fixed set of hand-written rules</button><button class="answer" data-correct="1">Training a multi-layer neural network on data</button><button class="answer" data-correct="0">Simply storing large datasets</button><p class="feedback"></p></div>`},
{title:"AI → ML → Deep Learning",lead:"How the key concepts relate",body:`<p>Artificial Intelligence is the broadest concept. Machine Learning is a subset of AI, and Deep Learning is a subset of Machine Learning.</p><div class="concepts"><article><b>AI</b><p>Systems performing tasks associated with intelligent behaviour.</p></article><article><b>ML</b><p>Algorithms that learn patterns from data.</p></article><article><b>DL</b><p>ML based on multi-layer neural networks.</p></article></div><div class="takeaway"><strong>Remember:</strong> Deep Learning ⊂ Machine Learning ⊂ Artificial Intelligence.</div>`}
]}}
;
let lang=localStorage.getItem("courseLang")||"uk",current=0;
const $=id=>document.getElementById(id);
function render(){const d=course[lang],s=d.sections[current];document.documentElement.lang=lang;$("heroTitle").textContent=lang==="uk"?"Основи глибокого навчання":"Fundamentals of Deep Learning";$("heroLead").textContent=lang==="uk"?"Від штучного нейрона до навчання нейронної мережі":"From an artificial neuron to neural-network learning";$("startBtn").textContent=d.start;$("prevLabel").textContent=d.prev;$("nextLabel").textContent=d.next;if(!$("lesson").classList.contains("hidden")){$("lessonNo").textContent=`${lang==="uk"?"РОЗДІЛ":"SECTION"} ${String(current+1).padStart(2,"0")} / 10`;$("lessonTitle").textContent=s.title;$("lessonLead").textContent=s.lead;$("lessonBody").innerHTML=s.body;$("progressBar").style.width=`${(current+1)*10}%`;bindAnswers();}}
function bindAnswers(){document.querySelectorAll(".answer").forEach(btn=>btn.onclick=()=>{const ok=btn.dataset.correct==="1";const f=document.querySelector(".feedback");f.textContent=ok?(lang==="uk"?"Правильно. Нейронна мережа навчається на даних, коригуючи свої параметри.":"Correct. The neural network learns from data by adjusting its parameters."):(lang==="uk"?"Не зовсім. Спробуйте ще раз.":"Not quite. Try again.");f.className=`feedback ${ok?"ok":"retry"}`;});}
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem("courseLang",lang);document.querySelectorAll("[data-lang]").forEach(x=>x.classList.toggle("active",x.dataset.lang===lang));render();});
$("startBtn").onclick=()=>{$("hero").classList.add("hidden");$("lesson").classList.remove("hidden");current=0;render();};
$("nextBtn").onclick=()=>{if(current<course[lang].sections.length-1){current++;render();}else{alert(lang==="uk"?"Наступні розділи зараз додаються до курсу.":"The next sections are being added to the course.");}};
$("prevBtn").onclick=()=>{if(current>0){current--;render();}else{$("lesson").classList.add("hidden");$("hero").classList.remove("hidden");$("progressBar").style.width="0";}};
render();