const course={
uk:{start:"Розпочати курс",prev:"Назад",next:"Далі",sections:[
{title:"Вступ",lead:"Що таке Deep Learning і навіщо воно потрібне",body:`<div class="learning"><strong>Навчальна мета</strong><p>Пояснити, що таке глибоке навчання та чому воно є важливим напрямом ШІ.</p></div><h3>Глибоке навчання — коротко</h3><p>Deep Learning — підхід машинного навчання, у якому багатошарові нейронні мережі навчаються знаходити складні закономірності у даних.</p><div class="flow"><span>Дані</span><b>→</b><span>Нейронна мережа</span><b>→</b><span>Навчання</span><b>→</b><span>Результат</span></div><div class="check"><h3>Міні-перевірка</h3><p>Що найкраще описує Deep Learning?</p><button class="answer" data-correct="0">Набір жорстко заданих правил</button><button class="answer" data-correct="1">Навчання багатошарової нейронної мережі на даних</button><button class="answer" data-correct="0">Зберігання великих масивів даних</button><p class="feedback"></p></div>`},
{title:"AI → ML → Deep Learning",lead:"Як пов’язані ключові поняття",body:`<p>Artificial Intelligence — найширше поняття. Machine Learning є його підмножиною, а Deep Learning — підмножиною ML.</p><div class="concepts"><article><b>AI</b><p>Системи, що виконують завдання, пов’язані з інтелектуальною поведінкою.</p></article><article><b>ML</b><p>Алгоритми, які навчаються закономірностям із даних.</p></article><article><b>DL</b><p>Машинне навчання на основі багатошарових нейронних мереж.</p></article></div><div class="takeaway"><strong>Запам’ятайте:</strong> Deep Learning ⊂ Machine Learning ⊂ Artificial Intelligence.</div>`},
{title:"Штучний нейрон",lead:"Найменший обчислювальний елемент нейронної мережі",body:`<div class="learning"><strong>Навчальна мета</strong><p>Зрозуміти, як вхідні дані перетворюються на вихід нейрона.</p></div><div class="neuron"><div class="inputs"><span>x₁</span><span>x₂</span><span>x₃</span></div><div class="arrow">→</div><div class="node">Σ<br><small>weights + bias</small></div><div class="arrow">→</div><div class="node activation">f(x)</div><div class="arrow">→</div><div class="output">ŷ</div></div><p>Кожен вхід має свою <strong>вагу</strong>. Нейрон об’єднує зважені входи, додає <strong>bias</strong> і передає результат через <strong>функцію активації</strong>.</p><div class="formula">z = w₁x₁ + w₂x₂ + … + b &nbsp; → &nbsp; y = f(z)</div><div class="takeaway"><strong>Просто:</strong> нейрон отримує сигнали → визначає їх важливість → формує вихід.</div>`},
{title:"Архітектура нейронної мережі",lead:"Input → Hidden Layers → Output",body:`<p>Нейрони об’єднуються у шари. Кожен наступний шар формує дедалі складніше представлення даних.</p><div class="layers"><article><b>INPUT</b><p>Отримує початкові ознаки.</p></article><span>→</span><article><b>HIDDEN 1</b><p>Виявляє прості закономірності.</p></article><span>→</span><article><b>HIDDEN 2+</b><p>Комбінує їх у складніші ознаки.</p></article><span>→</span><article><b>OUTPUT</b><p>Формує прогноз або клас.</p></article></div><div class="example"><strong>Приклад:</strong> для зображення ранні шари можуть реагувати на краї та лінії, глибші — на форми й частини об’єкта, а вихідний шар — визначати клас.</div>`},
{title:"Як навчається нейронна мережа",lead:"Prediction → Error → Update → Repeat",body:`<p>Навчання — це багаторазове коригування параметрів мережі, щоб зменшувати помилку.</p><div class="flow"><span>1. Дані</span><b>→</b><span>2. Прогноз</span><b>→</b><span>3. Помилка</span><b>→</b><span>4. Оновлення ваг</span><b>↻</b></div><div class="concepts"><article><b>Forward pass</b><p>Мережа робить прогноз.</p></article><article><b>Loss</b><p>Функція втрат вимірює помилку.</p></article><article><b>Backpropagation</b><p>Обчислюється внесок параметрів у помилку.</p></article><article><b>Optimizer</b><p>Ваги змінюються для зменшення loss.</p></article></div>`},
{title:"Застосування Deep Learning",lead:"Де багатошарові мережі дають практичну цінність",body:`<div class="applications"><article><b>👁 Computer Vision</b><p>Класифікація та аналіз зображень і відео.</p></article><article><b>🗣 Speech</b><p>Розпізнавання та синтез мовлення.</p></article><article><b>📝 Language</b><p>Аналіз, переклад і генерація тексту.</p></article><article><b>📡 Signals</b><p>Пошук закономірностей у складних потоках сигналів.</p></article></div><div class="takeaway"><strong>Важливо:</strong> якість результату залежить не лише від архітектури, а й від даних, метрики, обчислювальних ресурсів та людського контролю.</div>`},
{title:"Інтерактивний сценарій",lead:"Оберіть підхід для задачі",body:`<div class="scenario"><p><strong>Ситуація:</strong> потрібно автоматично розподілити велику колекцію зображень за відомими категоріями. Даних достатньо, а ознаки складно описати вручну.</p><p>Який підхід найбільш доречний у межах цього навчального прикладу?</p><button class="answer" data-correct="0">Створити вручну правило для кожного можливого зображення</button><button class="answer" data-correct="1">Навчити модель розпізнавати закономірності на прикладах</button><button class="answer" data-correct="0">Не використовувати дані для навчання</button><p class="feedback"></p></div>`},
{title:"Knowledge Check",lead:"Перевірте ключові поняття",body:`<div class="check"><h3>Що є підмножиною Machine Learning?</h3><button class="answer" data-correct="1">Deep Learning</button><button class="answer" data-correct="0">Усі бази даних</button><button class="answer" data-correct="0">Будь-яка комп’ютерна програма</button><p class="feedback"></p></div><div class="takeaway">Після відповіді переходьте до підсумкового оцінювання.</div>`},
{title:"Final Assessment",lead:"Підсумкова перевірка",body:`<div id="assessment"></div>`},
{title:"Summary",lead:"Ключові висновки",body:`<div class="summary"><h3>Ви пройшли модуль</h3><p>Тепер ви можете пояснити місце Deep Learning у структурі AI, базову роботу штучного нейрона, роль шарів мережі та загальний цикл навчання.</p><div class="flow"><span>AI</span><b>→</b><span>ML</span><b>→</b><span>DL</span><b>→</b><span>Neural Networks</span></div><p><strong>Головна думка:</strong> Deep Learning дає моделі змогу навчатися складним представленням із даних, але потребує належних даних, оцінювання та контролю.</p></div>`}
]},
en:{start:"Start course",prev:"Back",next:"Next",sections:[
{title:"Introduction",lead:"What Deep Learning is and why it matters",body:`<div class="learning"><strong>Learning objective</strong><p>Explain what deep learning is and why it is an important field of AI.</p></div><h3>Deep Learning — in brief</h3><p>Deep Learning is a machine-learning approach in which multi-layer neural networks learn complex patterns from data.</p><div class="flow"><span>Data</span><b>→</b><span>Neural Network</span><b>→</b><span>Learning</span><b>→</b><span>Result</span></div><div class="check"><h3>Mini check</h3><p>Which statement best describes Deep Learning?</p><button class="answer" data-correct="0">A fixed set of rules</button><button class="answer" data-correct="1">Training a multi-layer neural network on data</button><button class="answer" data-correct="0">Storing large datasets</button><p class="feedback"></p></div>`},
{title:"AI → ML → Deep Learning",lead:"How the key concepts relate",body:`<p>Artificial Intelligence is the broadest concept. Machine Learning is a subset of AI, and Deep Learning is a subset of ML.</p><div class="concepts"><article><b>AI</b><p>Systems performing tasks associated with intelligent behaviour.</p></article><article><b>ML</b><p>Algorithms that learn patterns from data.</p></article><article><b>DL</b><p>Machine learning based on multi-layer neural networks.</p></article></div><div class="takeaway"><strong>Remember:</strong> Deep Learning ⊂ Machine Learning ⊂ Artificial Intelligence.</div>`},
{title:"Artificial Neuron",lead:"The basic computational element of a neural network",body:`<div class="learning"><strong>Learning objective</strong><p>Understand how inputs are transformed into a neuron's output.</p></div><div class="neuron"><div class="inputs"><span>x₁</span><span>x₂</span><span>x₃</span></div><div class="arrow">→</div><div class="node">Σ<br><small>weights + bias</small></div><div class="arrow">→</div><div class="node activation">f(x)</div><div class="arrow">→</div><div class="output">ŷ</div></div><p>Each input has a <strong>weight</strong>. The neuron combines weighted inputs, adds a <strong>bias</strong>, and passes the result through an <strong>activation function</strong>.</p><div class="formula">z = w₁x₁ + w₂x₂ + … + b &nbsp; → &nbsp; y = f(z)</div><div class="takeaway"><strong>Simply:</strong> signals in → importance is weighted → an output is produced.</div>`},
{title:"Neural Network Architecture",lead:"Input → Hidden Layers → Output",body:`<p>Neurons are organised into layers. Successive layers can form increasingly complex representations of the data.</p><div class="layers"><article><b>INPUT</b><p>Receives initial features.</p></article><span>→</span><article><b>HIDDEN 1</b><p>Detects simple patterns.</p></article><span>→</span><article><b>HIDDEN 2+</b><p>Combines them into richer features.</p></article><span>→</span><article><b>OUTPUT</b><p>Produces a prediction or class.</p></article></div><div class="example"><strong>Example:</strong> for an image, early layers may react to edges, deeper layers to shapes and object parts, and the output layer to a class.</div>`},
{title:"How a Neural Network Learns",lead:"Prediction → Error → Update → Repeat",body:`<p>Training repeatedly adjusts network parameters to reduce error.</p><div class="flow"><span>1. Data</span><b>→</b><span>2. Prediction</span><b>→</b><span>3. Error</span><b>→</b><span>4. Weight update</span><b>↻</b></div><div class="concepts"><article><b>Forward pass</b><p>The network makes a prediction.</p></article><article><b>Loss</b><p>A loss function measures error.</p></article><article><b>Backpropagation</b><p>The contribution of parameters to error is calculated.</p></article><article><b>Optimizer</b><p>Weights are adjusted to reduce loss.</p></article></div>`},
{title:"Applications of Deep Learning",lead:"Where multi-layer networks create practical value",body:`<div class="applications"><article><b>👁 Computer Vision</b><p>Image and video classification and analysis.</p></article><article><b>🗣 Speech</b><p>Speech recognition and synthesis.</p></article><article><b>📝 Language</b><p>Text analysis, translation and generation.</p></article><article><b>📡 Signals</b><p>Finding patterns in complex signal streams.</p></article></div><div class="takeaway"><strong>Important:</strong> outcomes depend not only on architecture, but also on data, metrics, computing resources and human oversight.</div>`},
{title:"Interactive Scenario",lead:"Choose an approach for the task",body:`<div class="scenario"><p><strong>Situation:</strong> a large image collection must be automatically assigned to known categories. There is sufficient training data and useful features are difficult to specify manually.</p><p>Which approach is most appropriate for this learning example?</p><button class="answer" data-correct="0">Write a manual rule for every possible image</button><button class="answer" data-correct="1">Train a model to learn patterns from examples</button><button class="answer" data-correct="0">Do not use data for learning</button><p class="feedback"></p></div>`},
{title:"Knowledge Check",lead:"Check the key concepts",body:`<div class="check"><h3>Which is a subset of Machine Learning?</h3><button class="answer" data-correct="1">Deep Learning</button><button class="answer" data-correct="0">All databases</button><button class="answer" data-correct="0">Any computer program</button><p class="feedback"></p></div><div class="takeaway">After answering, continue to the final assessment.</div>`},
{title:"Final Assessment",lead:"Final knowledge check",body:`<div id="assessment"></div>`},
{title:"Summary",lead:"Key takeaways",body:`<div class="summary"><h3>You completed the module</h3><p>You can now explain where Deep Learning fits within AI, the basic operation of an artificial neuron, the role of network layers, and the overall training cycle.</p><div class="flow"><span>AI</span><b>→</b><span>ML</span><b>→</b><span>DL</span><b>→</b><span>Neural Networks</span></div><p><strong>Main idea:</strong> Deep Learning enables models to learn complex representations from data, while still requiring appropriate data, evaluation and oversight.</p></div>`}
]}}
;
const questions={uk:[["Deep Learning є…",["підмножиною Machine Learning","типом бази даних","операційною системою"],0],["Що змінюється під час навчання?",["Лише назва моделі","Ваги та інші параметри","Кількість вхідних даних автоматично"],1],["Для чого потрібна функція втрат?",["Вимірювати помилку прогнозу","Зберігати файли","Створювати нові класи"],0],["Що роблять hidden layers?",["Формують представлення ознак","Лише показують результат","Замінюють дані"],0],["Яка послідовність описує навчання?",["Прогноз → помилка → оновлення","Оновлення → видалення → прогноз","Зберігання → друк → прогноз"],0]],en:[["Deep Learning is…",["a subset of Machine Learning","a database type","an operating system"],0],["What changes during training?",["Only the model name","Weights and other parameters","The number of inputs automatically"],1],["What is a loss function used for?",["Measuring prediction error","Storing files","Creating new classes"],0],["What do hidden layers do?",["Build feature representations","Only display results","Replace the data"],0],["Which sequence describes training?",["Prediction → error → update","Update → delete → prediction","Storage → print → prediction"],0]]};
let lang=localStorage.getItem("courseLang")||"uk",current=0,score=0;
const $=id=>document.getElementById(id);
function assessment(){const box=$("assessment");if(!box)return;score=0;box.innerHTML=questions[lang].map((q,i)=>`<div class="assessment-q"><p><strong>${i+1}. ${q[0]}</strong></p>${q[1].map((a,j)=>`<button class="assessment-answer" data-q="${i}" data-a="${j}">${a}</button>`).join("")}</div>`).join("")+`<button id="submitAssessment" class="primary">${lang==="uk"?"Завершити оцінювання":"Submit assessment"}</button><div id="score"></div>`;document.querySelectorAll(".assessment-answer").forEach(b=>b.onclick=()=>{document.querySelectorAll(`.assessment-answer[data-q="${b.dataset.q}"]`).forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});$("submitAssessment").onclick=()=>{score=0;questions[lang].forEach((q,i)=>{const s=document.querySelector(`.assessment-answer.selected[data-q="${i}"]`);if(s&&+s.dataset.a===q[2])score++});$("score").innerHTML=`<div class="scorebox"><strong>${score}/5 — ${score>=4?(lang==="uk"?"Успішно":"Passed"):(lang==="uk"?"Перегляньте матеріал і спробуйте ще раз":"Review the material and try again")}</strong></div>`}}
function bindAnswers(){document.querySelectorAll(".answer").forEach(btn=>btn.onclick=()=>{const ok=btn.dataset.correct==="1",f=btn.parentElement.querySelector(".feedback");f.textContent=ok?(lang==="uk"?"Правильно.":"Correct."):(lang==="uk"?"Не зовсім. Спробуйте ще раз.":"Not quite. Try again.");f.className=`feedback ${ok?"ok":"retry"}`})}
function render(){const d=course[lang],s=d.sections[current];document.documentElement.lang=lang;$("heroTitle").textContent=lang==="uk"?"Основи глибокого навчання":"Fundamentals of Deep Learning";$("heroLead").textContent=lang==="uk"?"Від штучного нейрона до навчання нейронної мережі":"From an artificial neuron to neural-network learning";$("startBtn").textContent=d.start;$("prevLabel").textContent=d.prev;$("nextLabel").textContent=d.next;document.querySelectorAll("[data-lang]").forEach(x=>x.classList.toggle("active",x.dataset.lang===lang));if(!$("lesson").classList.contains("hidden")){$("lessonNo").textContent=`${lang==="uk"?"РОЗДІЛ":"SECTION"} ${String(current+1).padStart(2,"0")} / 10`;$("lessonTitle").textContent=s.title;$("lessonLead").textContent=s.lead;$("lessonBody").innerHTML=s.body;$("progressBar").style.width=`${(current+1)*10}%`;bindAnswers();if(current===8)assessment();}}
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem("courseLang",lang);render()});
$("startBtn").onclick=()=>{$("hero").classList.add("hidden");$("lesson").classList.remove("hidden");current=0;render()};
$("nextBtn").onclick=()=>{if(current<9){current++;render();window.scrollTo({top:0,behavior:"smooth"})}};
$("prevBtn").onclick=()=>{if(current>0){current--;render()}else{$("lesson").classList.add("hidden");$("hero").classList.remove("hidden");$("progressBar").style.width="0"}};
render();